name: Build and Deploy Sphinx to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme setuptools m2r
        pip install -r requirements.txt

    - name: Build Sphinx Documentation
      run: |
        cd docs  # Navigate to your Sphinx project directory
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GHPAGES_PAT }}
        publish_dir: ./docs/_build/html  # Adjust this path to your build output directory
        force_orphan: true
